learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_logs.urls')),
    path('users/',include('users.urls')),
]

learning_logs/urls.py
from django.urls import path

from . import views

app_name = 'learning_logs'

urlpatterns = [
    path('', views.index, name='index'),
    path('topics', views.topics, name='topics'),
    path('topics/<int:t_id', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    #auto_now_add=true - set this atribute to the current date and time
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        #it allows us to set a special attribute telling Django to use 'Entries'
        # when it needs to refer to more than one entry. Without this, Django
        # would refer to multiful entries as 'Entrys'
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        Model = Entry
        feilds = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Create your views here.

def index(request):
    return(request, 'learning_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}

    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')

    context = {'topic': topic, 'entries':entries}

    return render(request, 'learning_logs/topic.html', context)

#KNOW THIS FOR THE INTERVIEW PART OF THE EXAM
@login_required
def new_topic(request):
    if request.method != 'POST':
        #load up a blank form
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            
            return redirect('learning_logs:topics')

    context = {'form':form}

    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)

        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            form.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    
    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryFornm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            ###is this supposed to be t_id or Topic_id?
            return redirect('learning_logs:topic', t_id=topic.id)

    #context has all of the data that the html skeleton needs below
    context = {'entry' :entry, 'topic':topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
<p>
<a href="{% url 'learning_logs:index' %}">Learning Log</a>
<a href="{% url 'leanring_logs:topics' %}">Topics</a>

{% if user.is_authenticated %}
    Hello, {{user.username}}
    <a href="{% url 'users:logout' %}">Log out</a>
{% else %}
<a href="{% url 'users:register' %}"></a>
<a href="{% url 'users:login' %}"></a>
{% endif %}
</p>

{% block content %} 

{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry:</p>

<form action="{% url 'learning_logs:edit_entry' %}"method ='post'>
    {% csrf_token %}

    {{ form.as_p}}

    <button name="submit">Save changes</button>

</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "Learning_logs/base.html" %}

{% block content%}

    <p> Learning Log</p>

    <p>
    Learning Log helps you keep track of your learning, for any topuc you're learning about.
    </p>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>

<form action="{% url 'learning_logs:new_entry' %}"method ='post'>
    {% csrf_token %}

    {{ form.as_p}}

    <button name="submit">Add entry</button>

</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>Add a new topic</p>

<form action="{% url 'learning_logs:newtopic' %}"method ='post'>
    {% csrf_token %}

    {{ form.as_p}}

    <button name="submit">Add topic</button>


</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% entexds "learning_logs/basehtml" %}

{% block content %}

<p>Topic: {{ topic.text }}</p>

<ul>
    {% for e in entries %}

    <li>
        <p>{{ e.date_added|date:'M d, Y H:i' }}</p>

        <p>{{ e.text|linebreaks }}</p>

        <p>
            <a href="{% url 'learning_logs:edit_entry' e.id %}"></a>
        </p>
    </li>

    {% emplty %}

    <li> There are no entires for this topic yet.</li>

    {% endfor %}
</ul>

<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}"> Add new entry</a>
</p>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% entexds "learning_logs/basehtml" %}

{% block content %}

    <p>Topics</p>
    <ul>
        {% for topic in topics %}
            <li><a href="{% url 'learning_logs:topic' topics.id %}">{{ topic }}</a></li>
        {% empty %}
            <li>Not topics have been added yet.</li>
        {% endfor %}    
    </ul>

<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}